port: ":8080"

log:
  filename: "./code1024.log"
  maxSize: 10
  maxBackups: 5
  maxAge: 30

# mysql:
#   host: "127.0.0.1"
#   port: 3306
#   username: "root"
#   password: "123456"
#   database: "godb"

# mac
mysql:
  host: "127.0.0.1"
  port: 3306
  username: "root"
  password: "caushy777"
  database: "mydb"

redis:
  addr: "127.0.0.1:6379"
  password: "123456"
  db: 0

startTime: "2025-11-01"
machineID: 1

